Lx: 100
Ly: 100
Lz: 27
box_output: box.in
box_template: box_template.in
data_file: dataWCA.slit
dt: '0.0002'
dt0: '0.00001'
eps11: 1.0
eps12: 1.0
eps22: 0.0
fluid_gap: 13.0
lammps_exe: ~/lammps-29Aug2024/build/lmp
nodes: node02
potential_type: WCA
ppn: 4
queue: enp5
rcutLJ11: 3.2
rcutLJ12: 3.2
rcutLJ22: 3.2
rho_fluid: 0.6
rho_wall: 0.75
sig11: 1.0
sig12: 1.1
sig22: 1.2
simulation_name: LJ_H13_rho0_6
