Lx: 100
Ly: 100
Lz: 18
box_output: box.in
box_template: box_template.in
data_file: dataWCA.slit
dt: '0.002'
dt0: '0.0001'
eps11: 1.0
eps12: 1.0
eps22: 0.0
fluid_gap: 4.0
lammps_exe: ~/lammps-29Aug2024/build/lmp
nodes: node06
ppn: 8
queue: enp5
rcutLJ11: 3.82
rcutLJ12: 3.82
rcutLJ22: 3.82
rho_fluid: 0.6
rho_wall: 0.75
sig11: 1.0
sig12: 1.1
sig22: 1.2
simulation_name: LJ_H4_rho0_6
potential_type: WCA
