Lx: 100
Ly: 100
Lz: 24
box_output: box.in
box_template: box_template.in
data_file: dataWCA.slit
dt: '0.002'
dt0: '0.0001'
eps11: 1.0
eps12: 1.0
eps22: 0.0
fluid_gap: 10.0
lammps_exe: ~/lammps-29Aug2024/build/lmp
nodes: node01
ppn: 8
queue: enp5
rcutLJ11: 3.82
rcutLJ12: 3.82
rcutLJ22: 3.82
rho_fluid: 0.1
rho_wall: 0.75
sig11: 1.0
sig12: 1.1
sig22: 1.2
simulation_name: WCA_H10_rho0_1
